### ISSUE TITLE
Bootloop with your EFI

### ISSUE THREAD

**Issue by psylou** [DocSystem/razerbladehackintosh#6]
I wanted to upgrade to Big Sur, but I don't really know how.

When I try to boot your EFI, It crashes after hitting install macOS or when trying to boot catalina.

Sometimes it doesn't even show me the bootloader and goes straight to apple logo which then crashes

**Comment by DocSystem** [comment]
> Sometimes it doesn't even show me the bootloader and goes straight to apple logo which then crashes

![image](https://user-images.githubusercontent.com/42613513/124015013-80b44200-d9e4-11eb-88e5-0b1a286359f0.png)
To fix that, change the "ShowPicker" key to true.

And for the Big Sur crash, I will update the EFI soon, I already know this bug!

**Comment by DocSystem** [comment]
Just fixed everything in the latest 2 commits (https://github.com/DocSystem/razerbladehackintosh/commit/0f4a5f8fb5187f0473d9a4095f2e100f01bb0df8 + https://github.com/DocSystem/razerbladehackintosh/commit/9c07d2b900349c3b219149f0fd45e5ca5da78933) !

Try redownloading the EFI and retry!

**Comment by psylou** [comment]
sadly, it is still boot looping :(

I got no broadcom WIFI if thats a difference?

EDIT:  your newest commit (how do I reference them?) is also bootlooping for me :( 
Only vanilla mysticle EFI is working with Catalina for me right know. 

thanks for investing the time!

**Comment by DocSystem** [comment]
Okay!

The EFI is made for the original Blade's Intel Wifi so no that's not the problem...

But I have no idea of what caused the boot loop!

Can you send me what components do you have? (CPU and GPU)

This EFI is made for the Razer Blade 15 Base Model with:
* CPU: Intel Core i7-9750H
* dGPU: NVIDIA GeForce RTX 2060 / NVIDIA GeForce GTX 1660 (disabled in macOS)
* iGPU: Intel UHD Graphics 630

If you don't have this Razer Blade Model, this will be normal that the EFI needs adjustments!

You can also try remapping USB ports in macOS Catalina and replace my USBMap.kext with the one you generated! The boot loop can be caused by this kext!

**Comment by psylou** [comment]
I got exactly these specs with RTX 2060. The only difference is, that I'm using AX200 Wifi Card but it should be compatible with the kext you are loading. As mysticle says in his video I only changed preallocated to 64m in BIOS. Different from the old guide from stonevil who made some other changes to the bios like cfg-lock and stuff like that.

**Comment by psylou** [comment]
I know its hard to believe, but I finally fixed my Issue.
Adding -igfxblr -igfxmlr to the boot-args fixed it for me.

Last thing. Is your Razer Blade also draining battery so fast? even in sleep!

**Comment by DocSystem** [comment]
Sadly, yes
